name: build-and-test

on: [push]

jobs:
  build-selinuxd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos: ["8"]
    container:
      image: centos:${{ matrix.centos }}
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: yum -y --enablerepo=powertools install golang make libsemanage-devel
      - name: build selinuxd
        run: |
          make
          make test
