name: e2e
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  e2e-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: make fedora-image
      - run: podman save -o image.tar quay.io/jaosorior/selinuxd-fedora:latest
      - uses: actions/upload-artifact@v2
        with:
          name: fedora-image-tar
          path: image.tar

  e2e:
    needs: e2e-image
    runs-on: macos-10.15
    timeout-minutes: 80
    env:
      RUN: ./hack/ci/run.sh
      IMG: quay.io/jaosorior/selinuxd-fedora:latest
      CONTAINER_NAME: selinuxd
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: fedora-image-tar
          path: .
      - name: Boot Virtual Machine
        run: make vagrant-up
      - name: Run selinuxd
        run: $RUN hack/ci/daemon-and-trace.sh
      - name: Run E2E tests
        run: $RUN hack/ci/e2e.sh
      - name: Get logs
        run: $RUN hack/ci/logs.sh
        if: ${{ always() }}
      - name: Fetch selinuxd logs
        run: $RUN cat ${{ env.CONTAINER_NAME }}.logs > ${{ env.CONTAINER_NAME }}.logs
        if: ${{ always() }}
      - uses: actions/upload-artifact@v2
        with:
          name: e2e-fedora-logs
          path: ${{ env.CONTAINER_NAME }}.logs
        if: ${{ always() }}
      - name: Stop selinuxd
        run: $RUN podman stop ${{ env.CONTAINER_NAME }}
        if: ${{ always() }}
     #- name: Fetch seccomp profile
     #  run: $RUN cat /tmp/selinuxd-seccomp.json | python -m json.tool > selinuxd-seccomp.json
     #- uses: actions/upload-artifact@v2
     #  with:
     #    name: seccomp-profile
     #    path: selinuxd-seccomp.json
      - name: Fetch selinux policy
        run: $RUN cat selinuxd.cil > selinuxd.cil
      - uses: actions/upload-artifact@v2
        with:
          name: selinux-policy
          path: selinuxd.cil

  secure-e2e:
    needs: e2e-image
    runs-on: macos-10.15
    timeout-minutes: 80
    env:
      RUN: ./hack/ci/run.sh
      IMG: quay.io/jaosorior/selinuxd-fedora:latest
      CONTAINER_NAME: selinuxd
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: fedora-image-tar
          path: .
      - name: Boot Virtual Machine
        run: make vagrant-up
      - name: Run selinuxd
        run: $RUN hack/ci/daemon-secure.sh
      - name: Run E2E tests
        run: $RUN hack/ci/e2e.sh
      - name: Get logs
        run: $RUN hack/ci/logs.sh
        if: ${{ always() }}
      - name: Fetch selinuxd logs
        run: $RUN cat ${{ env.CONTAINER_NAME }}.logs > ${{ env.CONTAINER_NAME }}.logs
        if: ${{ always() }}
      - uses: actions/upload-artifact@v2
        with:
          name: e2e-fedora-logs
          path: ${{ env.CONTAINER_NAME }}.logs
        if: ${{ always() }}
      - name: Stop selinuxd
        run: $RUN podman stop ${{ env.CONTAINER_NAME }}
        if: ${{ always() }}
